// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.4.13.
// **********************************************************************

#ifndef __SERVICE_H_
#define __SERVICE_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "ComShare.h"
#include "servant/ServantProxy.h"
#include "servant/Servant.h"


namespace sole
{

    /* callback of async proxy for client */
    class ServicePrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~ServicePrxCallback(){}
        virtual void callback_wakeup(tars::Int32 ret,  const sole::Data& data)
        { throw std::runtime_error("callback_wakeup() override incorrect."); }
        virtual void callback_wakeup_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_wakeup_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Service_all[]=
            {
                "wakeup"
            };
            pair<string*, string*> r = equal_range(__Service_all, __Service_all+1, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Service_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_wakeup_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    sole::Data data;
                    _is.read(data, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response->context);

                    callback_wakeup(_ret, data);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<ServicePrxCallback> ServicePrxCallbackPtr;

    /* callback of coroutine async proxy for client */
    class ServiceCoroPrxCallback: public ServicePrxCallback
    {
    public:
        virtual ~ServiceCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Service_all[]=
            {
                "wakeup"
            };

            pair<string*, string*> r = equal_range(__Service_all, __Service_all+1, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Service_all)
            {
                case 0:
                {
                    if (msg->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_wakeup_exception(msg->response->iRet);

                        return msg->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        sole::Data data;
                        _is.read(data, 3, true);
                        setResponseContext(msg->response->context);

                        callback_wakeup(_ret, data);

                    }
                    catch(std::exception &ex)
                    {
                        callback_wakeup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_wakeup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<ServiceCoroPrxCallback> ServiceCoroPrxCallbackPtr;

    /* proxy for client */
    class ServiceProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 wakeup(const std::string & id,tars::Int64 eventId,sole::Data &data,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(eventId, 2);
            _os.write(data, 3);
            std::map<string, string> _mStatus;
            _mStatus.insert(std::make_pair(ServantProxy::STATUS_GRID_KEY, id));
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"wakeup", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(data, 3, true);
            return _ret;
        }

        void async_wakeup(ServicePrxCallbackPtr callback,const std::string &id,tars::Int64 eventId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(eventId, 2);
            std::map<string, string> _mStatus;
            _mStatus.insert(std::make_pair(ServantProxy::STATUS_GRID_KEY, id));
            tars_invoke_async(tars::TARSNORMAL,"wakeup", _os, context, _mStatus, callback);
        }
        
        void coro_wakeup(ServiceCoroPrxCallbackPtr callback,const std::string &id,tars::Int64 eventId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(eventId, 2);
            std::map<string, string> _mStatus;
            _mStatus.insert(std::make_pair(ServantProxy::STATUS_GRID_KEY, id));
            tars_invoke_async(tars::TARSNORMAL,"wakeup", _os, context, _mStatus, callback, true);
        }

        ServiceProxy* tars_hash(int64_t key)
        {
            return (ServiceProxy*)ServantProxy::tars_hash(key);
        }

        ServiceProxy* tars_consistent_hash(int64_t key)
        {
            return (ServiceProxy*)ServantProxy::tars_consistent_hash(key);
        }

        ServiceProxy* tars_set_timeout(int msecond)
        {
            return (ServiceProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "ServiceProxy"; }
    };
    typedef tars::TC_AutoPtr<ServiceProxy> ServicePrx;

    /* servant for server */
    class Service : public tars::Servant
    {
    public:
        virtual ~Service(){}
        virtual tars::Int32 wakeup(const std::string & id,tars::Int64 eventId,sole::Data &data,tars::TarsCurrentPtr current) = 0;
        static void async_response_wakeup(tars::TarsCurrentPtr current, tars::Int32 _ret, const sole::Data &data)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("tars_ret", _ret);
                tarsAttr.put("data", data);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (current->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["data"] = tars::JsonOutput::writeJson(data);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(data, 3);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __sole__Service_all[]=
            {
                "wakeup"
            };

            pair<string*, string*> r = equal_range(__sole__Service_all, __sole__Service_all+1, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __sole__Service_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    tars::Int64 eventId;
                    sole::Data data;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("id", id);
                        tarsAttr.get("eventId", eventId);
                        tarsAttr.getByDefault("data", data, data);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(eventId, _jsonPtr->value["eventId"], true);
                        tars::JsonInput::readJson(data, _jsonPtr->value["data"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(eventId, 2, true);
                        _is.read(data, 3, false);
                    }
                    tars::Int32 _ret = wakeup(id,eventId,data, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("tars_ret", _ret);
                            tarsAttr.put("data", data);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["data"] = tars::JsonOutput::writeJson(data);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(data, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
